LICENSE.md, README.md, ruby-on-rails/README.md, ruby-on-rails/docs/kickoff/README.md
Little refactors to be able to publish this repository
=> Minor refactors to publish repository

useful-scripts/docs/setup-environment.md
- Fixed wrong path in readme
- Changed sh to bash in readme
=> Fix for setup script path

infraestructure/aws/README.md, infraestructure/aws/docs/eb-possible-issues.md, infraestructure/aws/docs/eb-redis.md
* Added possible EB problems and solutions, inspired by my recent experience
* Added a doc that installs Redis in EB
=> Added EB possible issues doc and Redis install

ruby-on-rails/docs/other/useful-gems.md
Adding Debugging section to Useful Gems README
=> Adding Debugging Section to Useful Gems README

infraestructure/aws/README.md, infraestructure/aws/docs/ssl.md
Added to infrastucture/aws a step by step how to import a new SSL certificate
=> added AWS certificate information

infraestructure/aws/README.md, infraestructure/aws/docs/sns-basic-permissions.md
- Allows to use SNS Push Notifications
- Does not allow to create, modify or destroy Platform applications
=> Adds SNS Basic Permissions

ruby-on-rails/docs/other/useful-gems.md
=> Add the premailer-rails gem to usefull gems

README.md, net-core/README.md
=> Added netcore

useful-scripts/README.md, useful-scripts/docs/eb_environment_variable_checker.md, useful-scripts/scripts/repositories_to_check_example.json, useful-scripts/scripts/variable_checker.rb
Migrates script from infrastructure repository
=> Adds environment variables checker script

infraestructure/aws/docs/frontend-group.md
- Added a guide to create a policy with cdn invalidation permisses.
=> adding cdn invalidations policy

frontend/README.md, frontend/docs/cra-s3-compressed-deploy.md, frontend/docs/scripts/deploy-s3.js
* Added instructions for deploying create-react-app project to s3.
=> Added cra s3 deploy instructions

frontend/docs/style-guide.md
Added angular snippets section in angular section
=> added angular code snippets in style guide

frontend/docs/style-guide.md, react-native/README.md
* Added `node-requirer` and `js-hyperclick` to frontend atom packages
* Added `nuclide` and `react` to react native atom packages
* Fixed some links
=> Added frontend rn

frontend/docs/style-guide.md
Added atom packages:
* highlight-selected
* tab-foldername-index
=> Added two atom packages to frontend

testing/load-testing/README.md, testing/load-testing/batch.js, testing/load-testing/rails.js
Added batch and advanced examples for load testing Rails monolithic applications
=> Added batch load test example

ruby-on-rails/README.md
Added a useful link that explains the difference between Rails' includes, joins and eager_load
=> Added useful link to Rails include vs join methods

net-core/README.md, net-core/docs/kickoff/README.md
- Add kickoff guide
- Add new open source project link
- Add net core posts
=> update doc for NET Core

net-core/docs/kickoff/README.md
Add option for add or delete the auth module.
=> Add option for auth module

frontend/docs/style-guide.md
* Added gif screen recorders to frontend's tech-guide
* Removed unavailable tooltip
=> Gif generators

frontend/README.md, frontend/angular-js/README.md, frontend/layout/README.md, frontend/react/README.md
added open source libraries to the tech guides
=> [Front-End] added and reorganized Front-End's open source libraries.

useful-scripts/README.md, useful-scripts/docs/create-trello-card-via-form.md
Added script to create Trello card from a form response.
=> added new useful script

README.md
* Introduces bracket convention for PR names. The main idea is to filter incoming email notifications, and to enhance PR searching if needed.
=> [Wolox] Updating contributing guide

useful-scripts/README.md, useful-scripts/docs/copy-trello.md, useful-scripts/scripts/copyTrello.swift
This adds copy Trello corresponding READMEs and script to useful scripts section.
=> [Wolox] Add copyTrello to useful scripts

iOS/docs/kickoff/README.md
Add fastlane steps to iOS kickoff.
=> [iOS] Add fastlane copy to iOS kickoff

net-core/README.md
Add link, Migrating from .Net Core 1 to .Net Core 2.0
=> [NetCore] Add a new medium post in NetCore

frontend/react/README.md, frontend/react/docs/jest-enzyme-testing.md
Added a basic guide on how to test using jest and enzyme
=> [React] added basic testing guide.

nodejs/README.md, nodejs/docs/google app engine.md
- Adding google app engine guide to nodejs
=> [NodeJS] Google App Engine

net-core/docs/kickoff/README.md
###Summary
- little fix by changes in the bootstrap structure.
=> [NETCore] little change net core kickoff

useful-scripts/docs/setup-environment_mac.md, useful-scripts/scripts/setup_environment_mac.sh
Using same format as rails setup script.
It would be great if someone can test the zsh step that is the only missing testing.
If ruby version is already installed, it prompts the user for confirmation.
If fastlane credentials are already in the keychain, it shows a warning.
=> [iOS][Infrastructure] Adding ios setup script

infrastructure/README.md, infrastructure/docs/docker-guide.md, infrastructure/docs/docker/README.md, infrastructure/docs/docker/docs/docker-aws.md, infrastructure/docs/docker/docs/docker-heroku.md
- Add a Docker guide
- Add deploy in AWS using Docker
- Add deploy in Heroku using Docker
=> [Infrastructure] Add a docker guide with AWS and Heroku examples

infrastructure/docs/docker/docs/docker-aws.md
Documents how to deploy into AWS with multidocker
=> Document multidocker container

ruby-on-rails/README.md
- Just adding an article to RoR README
=> [RoR] Adding article on subcscription

ruby-on-rails/docs/other/vim-config.md
- A tutorial to install VIM;
- Some tips to use it;
=> [RoR / VIM] Add file: vim configuration (for rails)

react/react-native/README.md
Added react-native-redux-toast to the RN open source projects list
=> [React] Added redux toast to RN projects

frontend/README.md, frontend/docs/seo-guide.md
Add seo guide to frontend documentation.
=> [Front-End] Add seo guide

infrastructure/docs/docker/README.md, net-core/README.md
=> [NETCore] Add docker medium post

frontend/docs/css-style-guide.md
- Added example of pseudo-element and pseudo-class item
- Added `max-width` and `width` usage
=> [Frontend] Update css styleguide rules

ruby-on-rails/README.md, ruby-on-rails/docs/gem-tutorials/spree.md
- Add new directory `gem-tutorials` on RoR docs with a note on spree
gem;
- Add in RoR README link to VIM config and this new tuto;
=> [RoR - Spree gem] Add spree tutorial

net-core/README.md, net-core/docs/kickoff/README.md
- Update the kickoff's readme
- Add "Testing in .NET Core 2.0" post link
=> [.NETCore] Fixes for kickoff

iOS/README.md, iOS/docs/kickoff/README.md
Updating README with new open source projects and posts.
=> [iOS] Updated iOS README

ruby-on-rails/docs/gems/useful-gems.md
- Added active admin and administrate gems
=> [Rails] Add backoffice gems

ruby-on-rails/docs/gems/useful-gems.md
Added 4 profiler gems and analysis and profilers section
=> Added profiler gems

react/README.md, react/react-native/README.md, react/react/README.md
Couldn't find enough react native resources to make a Native specific section worth it
=> [React][React-Native] React section changes

.github/pull_request_template.md, README.md, git/README.md, git/docs/branch-protections.md, git/docs/git-configurations.md, git/docs/issue_template.md, git/docs/issues-good-practices.md, git/docs/pull-requests-good-practices.md, git/docs/pull_request_template.md, git/docs/releases-good-practices.md, iOS/README.md, iOS/docs/kickoff/README.md, templates/README.md, templates/docs/tech_kickoff.md, useful-scripts/scripts/setup-environment-mac.sh
Como parte del [documento de estándares](https://docs.google.com/document/d/1Iq5m2ZSxai7duGBba__SoMuCBGJPoRJCyoNW05X-Pbw/edit#) que surgió, actualicé las guías de git con lo que se ha hablado que estaría bueno que pase, e incluso las cosas que ya pasan.
=> [Git] Updating git practices

iOS/docs/kickoff/README.md
=> [IOS][FIX] fix-readme

net-core/README.md
=> [.NET Core] add-new-post

iOS/docs/kickoff/configure-ci/README.md
The Bitrise section didn't have any kind of references to the actual variables that you would need for the env vars section. I added a list of things you would need, plus a reference to your Technical Leader for the values you will be needing.
And Atom just removed some spaces because it's Atom.
=> [iOS] Clarified Bitrise env variables a little bit

react/react/README.md, react/react/docs/libraries/external-libraries.md
**Remember** to use the [corresponding tag](../README.md#contributing) in this PR's title.
- Added useful external libraries
- Added entries for internal and external libraries on main README
=> [React] Introducing external libraries

react/react/docs/libraries/external-libraries.md
- Added more external libraries
- Divided them in sections
- React-lottie does have a repo in travis but it's empty, so the build status is unknown
=> [React] Added more external libraries

README.md, java/README.md, java/docs/kickoff/README.md
With this PR we are going to add the complete doc for Java developers to use at Wolox
- Fix the kickoff section
- Build the structure and style guide section
=> [JAVA] Add the initial structure

react/react/README.md
**Remember** to use the [corresponding tag](../README.md#contributing) in this PR's title.
-Delete rewired link from react
https://trello.com/c/KsvwEKEA/7-sacar-react-app-rewired
=> [tech-guides]Delete rewired link from react

frontend/README.md, frontend/angular/README.md
- Added angular link in `/frontend` main page.
- Added `/frontend/angular` section with its template (Still under construction) 
https://trello.com/c/xKtm08b4/3-agregar-angular-al-tech-guides-de-front
=> [Tech-guide] Angular section

nodejs/README.md, nodejs/docs/jest.md
- Add wolox node medium posts in the documentation.
- Add Jest getting started doc to node documentation.
=> [Node] Add medium posts and Jest doc to Node.js documentation

nodejs/README.md, nodejs/docs/sequelize/group_by_and_aggregation_functions.md
This document expose an hypothetic case to use `group by` and `aggregation` functions together.
=> [SEQUELIZE] Added document: how to group by and use aggregation functions

nodejs/README.md
I am adding the link for _Documenting a NodeJS REST API with OpenApi 3/Swagger_ post.
=> [NodeJS] Adding post about documenting a NodeJS REST API with OpenApi 3/Swagger

frontend/README.md
Delete  usefull documentation  an relocate inner items
=> [TECH] Delete  usefull documentation

nodejs/docs/sequelize/specific_details.md
I am adding a new file for documenting weird things about Sequelize. I put the one I had trouble with.
=> [NodeJS] Sequelize specific details

nodejs/README.md, nodejs/docs/sequelize/validations_in_bulk_methods.md
- Renaming validation in bulks methods guide
- Linking guide to NodeJS index
=> [NodeJS] fixing names and linking in sequelize docs

frontend/angular-js/README.md, frontend/angular/README.md, frontend/layout/README.md, frontend/react/README.md, frontend/vue/README.md
- Replaced `content` for `index` in all FE techs
https://trello.com/c/ewjoq9FO
=> [FE Techs] Index

frontend/angular-js/README.md, frontend/angular/README.md, frontend/layout/README.md, frontend/vue/README.md
- Deleted `under construction` text from all Front-End tech guides.
https://trello.com/c/JZalTVnU
=> [FE Techs] Under construction text

frontend/angular/README.md, frontend/angular/docs/kickoff.md
- I create angular kickoff guide
https://trello.com/c/EiY1Of8y/23-crear-documento-de-guia-de-kickoff-de-angular-vacio-y-hablar-con-bootstrap-squad-para-generar-guia
=> [Angular] Create angular kickoff guide

ruby-on-rails/docs/gems/tutorials/pushing_gems.md
A small guide for ruby developers to push their new gems correctly.
=> [RoR] Guide for pushing Gems

frontend/docs/style-guide.md
- Added indentation rule to front end style guides.
=> [Tech Guides] Indentation Rule

nodejs/README.md, nodejs/docs/node-standard-and-best-practices.md
* Added nodejs standard and best practices document.
=> [Node] Added nodejs standard and practices

frontend/angular/README.md, frontend/vue/README.md, frontend/vue/docs/kickoff.md
- I add Vue kickoff.
- I fix angular kickoff link.
https://trello.com/c/J1Ju1mqx/33-relevar-kickoff-guide-de-vue
=> [Vue]Vue kickoff

nodejs/docs/node-standard-and-best-practices.md
Fixed some typos and grammar issues
=> [NodeJS] Standards and best practices fixes

nodejs/docs/node-standard-and-best-practices.md
Added somethings about output parameters and rest api. Fixed some links.
=> [NodeJS] Standards and best practices updates and links fixes

nodejs/docs/node-standard-and-best-practices.md
Fixing text in AND OPERATOR section
=> Fixing text in AND OPERATOR section

nodejs/docs/node-standard-and-best-practices.md
Adding Swtch dictionary section
* _My editor deleted a bunch of trailing spaces_
=> [NodeJs] Updating tech-guides Adding Swtch dictionary section

nodejs/docs/node-standard-and-best-practices.md
- Add more functions in the programming section.
- Add ES6 section.
=> [NodeJs] Add es6 in node js best practices

nodejs/docs/node-standard-and-best-practices.md
Fixing anchor link to switch section
Fixing typo
=> Fixing anchor link to switch section

nodejs/README.md, nodejs/docs/sequelize/migrations_and_model_definition.md
- How to define models with define method with Sequelize.
- How to create migrations with Sequelize.
- How to use operators with examples.
- None
=> [NodeJS] Add section: How to define migrations, models and use operators with Sequelize

backend/backend-standard-and-best-practices.md
- Added the common standards and best practices for the backend department.
=> [Backend] Added general standards and best practices

frontend/react/style-guide.md
**Remember** to use the [corresponding tag](../README.md#contributing) in this PR's title.
Adding typescript section to the react style guide.
=> [React] React styleguide: Adding typescript

nodejs/docs/node-standard-and-best-practices.md
- Updated response guidelines following [API RESTful guidelines](https://docs.google.com/document/d/12FBRk7BLujkxY9K-eyKl3hiyu7aDzV2Xo2kcLlb505A/edit#heading=h.b56ouulzac4a).
=> [Node-JS] Updated Response Guidelines

nodejs/docs/sequelize/migrations_and_model_definition.md
- Fixed a very important typo.
=> [Node-JS] Fixed typo

nodejs/docs/node-standard-and-best-practices.md, nodejs/docs/sequelize/transactions.md
- Add document transactions.md in /nodejs/docs/sequelize
=> [NodeJS] Adding transactions info for Sequelize

nodejs/README.md
Add transactions section in node README
=> [NodeJS] Add transactions section in node README

README.md, integrations/README.md, integrations/payment_methods/web_pay.md
- Adding new section integrations
- Adding webpay documentation
=> New section integrations

frontend/vue/README.md, frontend/vue/docs/.vuerc, frontend/vue/docs/kickoff.md
=> [Vue] Update vue kickoff guide

react-native/pull-requests-good-practices.md
Adds a document about creating and reviewing PRs in RN. This isn't a complete document, but it's a place for people to make contributions with more tips.
=> [React-Native] Add RN PR guide

react-native/README.md, react-native/docs/environment-setup.md
Hi! Here is a doc on how to setup a React Native development environment.
=> [React Native] Environment setup

infrastructure/docs/aws/docs/terraform.md
Adds readme on how to create infrastructure with terraform.
=> Adds terraform documentation

frontend/angular/style-guide.md
Add new bullets with information about the ordering of methods.
=> [Angular] add information to angular style guide

frontend/angular/style-guide.md
Fix typing errors in the Angular guide.
=> fix: typing errors

frontend/vue/README.md, frontend/vue/style-guide.md
Add following items to the Vue Style Guide:
- Alignment
- Quotes
- Spacing
=> Add alignment, quotations, spacing. Also fix the link to the style guide.

frontend/README.md, frontend/docs/text-editors.md
- Remove suggestion of Atom as editor recommended!
#219
=> Remove Atom editor support

frontend/angular/style-guide.md
Add information about how to load components dynamically since version 13.*.
=> feat: add dynamic loading component info.

frontend/react/style-guide.md
- add info about the use of the refs with hooks.
Missing information about hooks #219
=> [React] Refs - style guide

frontend/react/style-guide.md
- React-Query Basic Docs based on training
=> docs: add react-query to react docs

frontend/react/style-guide.md
Guide about how implement good practices of useState and useEffect hooks
=> React - doc useState, useEffect Hooks

frontend/react/style-guide.md
Updated the React style guide to reflect the preference for using functional components over class components.
N/A
=> [Front-End][React] Update style guide - Prefer functional components

frontend/react/README.md, frontend/react/style-guide.md
- Fix the link to Wolox React Style Guide
- Modify the Folder structure
- Clean the layout examples
- Add an example of Context
N/A
=> [Front-End][React] Update style guide - Remove layout component and add use of context

frontend/react/style-guide.md
**Remember** to use the [corresponding tag](../README.md#contributing) in this PR's title.
Upgrade all JSX code to TSX from React style guide
=> Migrate JSX code to TSX code in React Style Guide

frontend/NextJs/README.md, frontend/NextJs/style-guide.md, frontend/README.md, frontend/react/style-guide.md, package-lock.json
Initial version of Wolox style guide of Nextjs framework with the principal topics about the tech.
N/A
N/A
=> [NextJS]Style guide V1
